### ISSUE TITLE
Volar suddenly being forced?

### ISSUE THREAD

**Issue by AasmundEndresen** [sdras/vue-vscode-snippets#105]
I just logged on to start working - and now every single vue file in my project is getting marked with an error message from Volar on every single line, even though I've been using Vetur for my project.  This extension was being marked as the culprit.  Can you please revert whatever changes you made?

**Comment by sdras** [comment]
Oh interesting, I got a lot of feedback that people wanted to see Volar as the dependency, thanks for letting me know. I'm removing any extension dependencies.
