### ISSUE TITLE
Snippets for WebStorm 

### ISSUE THREAD

**Issue by prigara** [sdras/vue-vscode-snippets#11]
Hi!
My name is Ekaterina and I'm from the [WebStorm](https://www.jetbrains.com/webstorm/) team. 
Thank you for building this collection of code snippets! We really like it! 
We want to ask you permission to adapt them for WebStorm (and all other JetBrains IDEs) and make available as part of the Vue.js plugin we have. The plugin is [open source](https://github.com/JetBrains/intellij-plugins/tree/master/vuejs), however, it only works with the paid IDE we have. 
Thanks!

**Comment by chendayang** [comment]
hi, does  it support user to  define Snippets?
for example, I want 'vbase' add something, like method, data,etc

**Comment by prigara** [comment]
When the snippets are adapted and bundled with WebStorm, one can type the abbreviation in the editor and then hit Tab to expand it. Did that answer your question? I'm not sure I understood it correctly.

**Comment by sdras** [comment]
Hi @prigara, you sure can! It would be nice if you could credit me and/or this repo somewhere in your repo :) Have at it!

**Comment by prigara** [comment]
Great, thank you! :) Yes, sure, we will add a link.
