### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by logiclabs** [sdras/vue-vscode-snippets#23]
It would be nice if these were available to typescript code as well.

With vetur, typescript snippets will work in a <script lang="ts"> section. Think the snippets just need to be registered as "typescript", as well as javascript.

**Comment by sdras** [comment]
Oh, gotcha! Yes I will work on that, thanks for filing this.

**Comment by sdras** [comment]
I haven't had the time to dive into this but I would accept a PR for it 🤘

**Comment by sdras** [comment]
This is merged! Thank you @LissetteIbnz!
