### ISSUE TITLE
Vue Router Snippets

### ISSUE THREAD

**Issue by Christhofernatalius** [sdras/vue-vscode-snippets#34]
Please add snippets for vue-router

**vroutename**
`<router-link :to="{name: 'foo'}">link to foo</router-link>`

**vroutepath**
`<router-link to="/foo">link to foo</router-link>`

And if possible, also include params/query
`<router-link :to="{name: 'foo', params:{id: 2}}">link to foo</router-link>`

Typing this is very tedious, and idk why, my vue custom snippets not working.

**Comment by sdras** [comment]
This is merged! Thank you @maatthc :)

**Comment by Christhofernatalius** [comment]
Very nice, thank you @maatthc @sdras
