### ISSUE TITLE
Remove scss as default style lang attribute in vbase

### ISSUE THREAD

**Issue by gilesbutler** [sdras/vue-vscode-snippets#44]
Hey,

Thanks for the awesome snippets! I'm not sure when this changed, fairly recently, but the style's lang attribute in `vbase` now defaults to `scss`. I have to delete it every time I use `vbase` which is pretty often. Can we revert it back to what it was if possible?

Thanks

```
<style lang="scss" scoped>

</style>
```

**Comment by lyfan13** [comment]
![vuejson](https://user-images.githubusercontent.com/46513492/56384663-913ad080-624f-11e9-82c6-3f7a8715be10.png)
you can fix it by change edit this extension's json file .
for my computer the {vue.json} , I change the 'scss' to 'stylus' .
in my computer this json file' directory is "C:\Users\Administrator\.vscode\extensions\sdras.vue-vscode-snippets-1.6.0\snippets\vue.json" , you can find your own then.

**Comment by gilesbutler** [comment]
Ah ok, thanks @lyfan13 - I'm on a mac so I'll try find that file.

Won't this get overwritten though if the extension updates?
