### ISSUE TITLE
亲，为啥默认vbase默认生成的style是scss呢，能参数自定义不？

### ISSUE THREAD

**Issue by xiaopohair** [sdras/vue-vscode-snippets#50]
<template>
    <div>

    </div>
</template>

<script>
    export default {
        
    }
</script>

<style lang="scss" scoped>

</style>

**Comment by sdras** [comment]
For others, it says: As the default vbase default generated style is scss, can the parameters be customized?

Yes! I'll fix it up to have this selected when it's first output so that you can delete easily or refactor.

PRs also welcome.

**Comment by sdras** [comment]
For now, the scss isn't highlighted yet but there's a new release where you can use `vbase-css` and it outputs just the css
