### ISSUE TITLE
pug snippets do not work

### ISSUE THREAD

**Issue by teleyinex** [sdras/vue-vscode-snippets#56]
I've not been able to use any of the pug snippets. I guess, it could be related to the snippet configuration. Can you check it?

**Comment by sdras** [comment]
I don't use pug for anything but creative coding projects, I can check but I'm low on time. @amandaporto, you were the contributor here, is it working for you? Is there any insight you have here? Thanks everyone.

**Comment by amandaporto** [comment]
Funnily enough, they stopped working for me as well. I've been meaning to look into it, but am also running low on time lately. Hoping to get some time in the next couple of weeks. 🤞🏼

**Comment by teleyinex** [comment]
Let me know if I can help :-) The thing is that I use nvim coc to run thoese snippets, so I don't have the regular environment.

**Comment by sdras** [comment]
Should be fixed now, thanks!
