### ISSUE TITLE
Incompatible with older version of code (<1.15)

### ISSUE THREAD

**Issue by fussinatto** [sdras/vue-vscode-snippets#6]
Trying to install extension on older version(I run 1.14.2) of code trows an error:
> Couldn't find a compatible version of Vue VSCode Snippets with this version of Code.

Downgrading vscode verision of engines in package would solve the problem.
It would be nice to support >=1.14, but feel free to close this issue if you don't see benefit of downgrading.

**Comment by sdras** [comment]
You're not the only person to stumble on this, so I just downgraded the requirement :) I just tested it out on another machine, seems to be working. Feel free to reopen the issue if you run into any problems 🤘🏼

Thanks!
