### ISSUE TITLE
bug in beforeEach and afterEach?

### ISSUE THREAD

**Issue by epfromer** [sdras/vue-vscode-snippets#60]
First off, excellent set of snippets, thank you.

I'm walking through them all, and think I may have found bugs in beforeEach and afterEach for the Vue Router set.  

I believe each should have a closing paren to match the opening.  That is, for beforeEach:

`"Vue Router beforeEach": {
"prefix": "vbeforeeach",
"body": [
"router.beforeEach((to, from, next) => {",
"\t${1:next();}",
"};"
],
"description": "Vue Router global guards beforeEach"
},`

should be:

`"Vue Router beforeEach": {
"prefix": "vbeforeeach",
"body": [
"router.beforeEach((to, from, next) => {",
"\t${1:next();}",
"});"
],
"description": "Vue Router global guards beforeEach"
},`

**Comment by zwik** [comment]
As @sdras merged my PR, this should be resolved. There's a new release as well so if you update your extension you should be fine.

**Comment by sdras** [comment]
Thanks!
