### ISSUE TITLE
vrouter snippet bug

### ISSUE THREAD

**Issue by iampeternguyen** [sdras/vue-vscode-snippets#65]
vrouter snippet has a curly brace where it should be a bracket.

`import Vue from 'vue';
import VueRouter from 'vue-router';

Vue.use(VueRouter);

export const router = new VueRouter({
  base: '/',
  mode: 'history',
  routes: [
    { path: '/path', component: component }
  }
});`

**Comment by sdras** [comment]
fixed! updating now, should take a minute or two to publish
