### ISSUE TITLE
Would you consider an additional snippet for typescript, vue-property-decorator users?

### ISSUE THREAD

**Issue by sr33** [sdras/vue-vscode-snippets#72]
Something like this would be useful for folks who use the library, [vue-property-decorator](https://github.com/kaorun343/vue-property-decorator) for class styled components, and decorators.
```

<template>
  <div></div>
</template>

<script lang="ts">
import { Vue, Component, Prop } from 'vue-property-decorator';

@Component
export default class MyComponent extends Vue {
}
</script>
```

Thank you for these excellent snippets by the way.

**Comment by sdras** [comment]
Definitely. There's another TypeScript PR but that one is a bit stale, please feel free to PR :)

**Comment by sdras** [comment]
Merged! Thanks!
