### ISSUE TITLE
How to edit v-base template ? 

### ISSUE THREAD

**Issue by steveyang331** [sdras/vue-vscode-snippets#82]
How to edit v-base template ? 

Thank you

**Comment by Brainyac** [comment]
You can either edit the template in the snippet folder (Command in VSC: `Open Extension Folder` and then go to `sdras.vue-vscode-snippets-xxx`). 

However those changes will be overwritten with an update of the extension. 
Instead I'd create a new snippet and copy paste the snippets from there and change it to your liking.

**Comment by sdras** [comment]
What @Brainyac said :)

There are a few different versions of vbase now, maybe there's one that fits your needs. Open to PRs too!
