### ISSUE TITLE
Snippets overview recommendation

### ISSUE THREAD

**Issue by robole** [sdras/vue-vscode-snippets#83]
Hi Sarah,

I'm a happy user of this extension. Thank you! 🙂

I would like to recommend an easy way to get an overview of the snippets. Maybe I can add this as recommendation to the README?

I switch between technologies regularly, which makes me prone to forget prefixes. To compensate for this, I wrote an extension that gives a nice UI for all available snippets. It is called [Snippets Ranger](https://marketplace.visualstudio.com/items?itemName=robole.snippets-ranger), you can see a screenshot below. It's on the right.

![vue-snippets](https://user-images.githubusercontent.com/3703647/93910671-027b8e80-fd34-11ea-9b2e-54c915630f75.png)

While your README is ship-shape, others are not so conscientiousness! In any case, I find it great to have them all at my fingertips, with a few keystrokes, just like a snippet! It's a nice little win!

If you don't think it's appropriate, no problemo! 🙂

Best wishes

Rob

**Comment by sdras** [comment]
Oh I love this! Please feel free to PR the readme, I would personally find this useful! Thanks

**Comment by robole** [comment]
Glad to hear it 😎 I added a PR @sdras

**Comment by sdras** [comment]
Closing this out due to the PR being closed but open to a new PR
