### ISSUE TITLE
Does this extention supports all version of vue? 2 to 3?

### ISSUE THREAD

**Issue by BroJenuel** [sdras/vue-vscode-snippets#87]
Does this extention supports all version of vue? 2 to 3?

**Comment by sdras** [comment]
It supports both- you can see the snippets that say 3 in the title and this whole section: [https://github.com/sdras/vue-vscode-snippets#vue-composition-api](https://github.com/sdras/vue-vscode-snippets#vue-composition-api)

Options API is still supported in Vue 3 as well, so they are not deprecated.
