### ISSUE TITLE
[Request] Publish extension on open-vsx.org

### ISSUE THREAD

**Issue by oxy** [sdras/vue-vscode-snippets#93]
Hi there!

I'm reaching out to you because we currently have your extension manually added to our extension gallery at Coder for [code-server](https://github.com/cdr/code-server/), and we're currently working on a migration to open-vsx, which is also used by other community VSCode forks (including, but not limited to Arch Linux's Code-OSS builds and VSCodium).

We (and other open source VSCode forks) cannot use Microsoft's extension gallery, as MS' terms of service allows only the proprietary MS products to interact with the official gallery.

We'd really appreciate it if you can add your extension to open-vsx! A simple guide on publishing extensions to Open-VSX is available [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by good-praxis** [comment]
Oh how fitting, I was just running into the issue of not finding it listed in the marketplace (running a Code-OSS built) and didn't quite understand why it wasn't showing up. As someone who is working through your FEM courses right now, I support this request fully.

**Comment by ArsalaBangash** [comment]
It's unfortunate that this issue hasn't received the attention it deserves. I'd like to setup gitpods for my students with Vue's best extensions preloaded.

**Comment by sdras** [comment]
This looks cool! I'll check it out after work. Thanks!

**Comment by sdras** [comment]
I spent a while setting up an account and getting things sorted and ran into errors- to be honest, I'm not sure I care enough about hosting it here to debug on my weekends. If one of you cares a lot and wants to host it there, please have at it. Just credit this repo.

**Comment by Neluji** [comment]
Hi !
Sorry to dig this up but I noticed that since you closed it you have published your Night Owl theme on open-vsx since, do you think now it would be easier/possible for you to publish this extension as well ?
As mentioned initially, I think it would be really appreciated by users of VSCode-compatible editors that rely on open-vsx 😁
(PS: sorry if a comment here is not the right way to do ^^')
